name:                memory-store
version:             0.1.0.0
github:              "githubuser/memory-store"
license:             BSD3
author:              "Milan Suk"
maintainer:          "milansuk@email.cz"
copyright:           "2021 Milan Suk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/memory-store#readme>

dependencies:
- base >= 4.7 && < 5
- network
- bytestring
- containers

library:
  source-dirs: src

executables:
  memory-store-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memory-store

tests:
  memory-store-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memory-store
